---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=600']

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint-cli2
        description: Run markdownlint-cli2 on your Markdown files using the docker image
        language: docker_image
        types: [markdown]
        entry: 'davidanson/markdownlint-cli2-rules:latest'
        args: ['--config', '.github/.markdownlint.json']

...
