---

version: '3.9'

services:
  app:
    image: wayofdev/php-dev:8.1-fpm-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: on-failure
    networks:
      - default
      - platform
    depends_on:
      - database
    links:
      - database
    external_links:
      - "rabbitmq.${PROJECT_SERVICES_NAMESPACE}.alias:rabbitmq"
    environment:
      APP_NAME: $APP_NAME
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
      - ~/.composer:/.composer

  web:
    image: wayofdev/nginx:k8s-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}_web
    restart: on-failure
    networks:
      default:
      shared:
      platform:
        aliases:
          - ${APP_NAME}.${COMPOSE_PROJECT_NAME}.alias
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./app:/app:rw,cached
      - ./.env:/app/.env
      - ./certs:/etc/nginx/ssl
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-${APP_NAME}-${COMPOSE_PROJECT_NAME}-secure.rule=Host(`api.${APP_NAME}.${PROJECT_SERVICES_NAMESPACE}.docker`)
      - traefik.http.routers.api-${APP_NAME}-${COMPOSE_PROJECT_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.api-${APP_NAME}-${COMPOSE_PROJECT_NAME}-secure.tls=true
      - traefik.http.services.api-${APP_NAME}-${COMPOSE_PROJECT_NAME}-secure.loadbalancer.server.port=8443
      - traefik.http.services.api-${APP_NAME}-${COMPOSE_PROJECT_NAME}-secure.loadbalancer.server.scheme=https

  database:
    image: wayofdev/postgres:15-alpine-latest
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: on-failure
    networks:
      platform:
        aliases:
          - database.${APP_NAME}.${COMPOSE_PROJECT_NAME}.alias
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_data:/var/lib/postgresql/data:cached

volumes:
  database_data:

networks:
  shared:
    external: true
    name: ${SHARED_SERVICES_NETWORK}
  platform:
    external: true
    name: project.${PROJECT_SERVICES_NAMESPACE}

...
